os: linux
language: node_js
node_js: stable
sudo: true

addons:
  apt:
    packages:
    # iohook
    - libx11-dev
    - libxtst-dev
    - libxt-dev
    - libx11-xcb-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
    # robotjs
    - libxtst-dev
    - libpng++-dev
script:
- npm ci --production
- npm install
- npm run rebuild
