language: node_js
node_js: 
  - 'node'
cache: npm
stages:
  - name: prepare_release
    if: branch = master AND tag != ""
  - build_and_deploy

jobs:
  include:
    - stage: prepare_release
      os: windows
      before_install:
      - echo $TRAVIS_TAG
      - data_row="{\"tag_name\":\"$TRAVIS_TAG\",\"target_commitish\":\"master\",\"name\":\"$TRAVIS_TAG\"}"
      - echo $data_row
      - "curl --location --request POST 'https://api.github.com/repos/xiekun1992/lan_control/releases' \
          --header 'Content-Type: application/json' \
          --header \"Authorization: token $github_personal_access_token\" \
          --data-raw $data_row"
      install: skip
      script: echo 'prepared'

    - stage: build_and_deploy
      os: linux
      addons:
        apt:
          sources:
          - sourceline: 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
            key_url: 'https://dl.winehq.org/wine-builds/winehq.key'
          update: true
          packages:
          - p7zip-full
          # iohook
          - libx11-dev
          - libxtst-dev
          - libxt-dev
          - libx11-xcb-dev
          - libxkbcommon-dev
          - libxkbcommon-x11-dev
          # robotjs
          - libxtst-dev
          - libpng++-dev
          # wine
          # - winehq-stable
      before_script:
      - npm run rebuild
      - npm install electron-packager -D
      script: 
      - npx electron-packager .
      - 7z a lan_control-linux-x64.zip lan_control-linux-x64/ > /dev/null
      - ls
      after_script:
      - "curl --location --request GET \"https://api.github.com/repos/xiekun1992/lan_control/releases/tags/$TRAVIS_TAG\" > res.txt"
      - cat res.txt
      - node .travis-ci/jattr.js res.txt id r.txt
      - releaseId=$(cat r.txt)
      - echo $releaseId
      - echo $github_personal_access_token
      - "curl --location --request POST \"https://uploads.github.com/repos/xiekun1992/lan_control/releases/$releaseId/assets?name=lan_control-linux-x64.zip\"
        --header \"Authorization: token $github_personal_access_token\" \
        --header 'Content-Type: application/zip' \
        --data-binary '@lan_control-linux-x64.zip'"

    - stage: build_and_deploy
      os: windows
      before_script:
      - npm run rebuild
      - npm install electron-packager -D
      script:
      - npx electron-packager .
      - 7z a lan_control-win32-x64.zip lan_control-win32-x64/
      - dir
      after_script:
      - "curl --location --request GET \"https://api.github.com/repos/xiekun1992/lan_control/releases/tags/$TRAVIS_TAG\" > res.txt"
      - cat res.txt
      - node .travis-ci/jattr.js res.txt id r.txt
      - releaseId=$(cat r.txt)
      - echo $releaseId
      - echo $github_personal_access_token
      - "curl --location --request POST \"https://uploads.github.com/repos/xiekun1992/lan_control/releases/$releaseId/assets?name=lan_control-win32-x64.zip\"
        --header \"Authorization: token $github_personal_access_token\" \
        --header 'Content-Type: application/zip' \
        --data-binary '@lan_control-win32-x64.zip'"
