os: linux
language: node_js
node_js: stable
sudo: true

addons:
  apt:
    sources:
    - sourceline: 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
      key_url: 'https://dl.winehq.org/wine-builds/winehq.key'
    packages:
    # iohook
    - libx11-dev
    - libxtst-dev
    - libxt-dev
    - libx11-xcb-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
    # robotjs
    - libxtst-dev
    - libpng++-dev
    # wine
    - winehq-stable

before_install:
- echo 'before_install'
- dpkg --add-architecture i386 
install:
- echo 'install'
before_script:
- echo 'before_script'
script:
- npm ci --production
- npm install
- npm run rebuild
- npm install electron-packager -D
- npx electron-packager . --all
- ls -l
# - zip -r 
after_success:
- echo 'after_success'
after_failure:
- echo 'after_failure'
before_deploy:
- echo 'before_deploy'
deploy:
- echo 'deploy'
after_deploy:
- echo 'after_deploy'
after_script:
- echo 'after_script'